###Signup
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "JudeSedem",
    "email": "judefiadza@gmail.com",
    "password": "Pass123"
}

###Login
POST http://127.0.0.1:8000/api/token/
Content-Type:application/json

{
    "username": "JudeSedem",
    "password": "Pass123"
}

###Create reminders
POST http://127.0.0.1:8000/api/reminders/
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTU5ODQwLCJpYXQiOjE3NjU1NTYyNDAsImp0aSI6IjRmNzBiZDg2NjkwYjQxYjRiMWUwNDFkYmI3Y2JmZGU2IiwidXNlcl9pZCI6IjEifQ.8-LrNhAMN1-27Lw1vyLmFHSlpnC9EcdKo7kI6vSCdBo

{
  "title": "Meeting with Gibson",
  "note": "Presenting project",
  "scheduled_time": "2025-12-12T16:20:00Z",
  "frequency": "O"
}


###Listing all reminders
GET http://127.0.0.1:8000/api/reminders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTU5ODQwLCJpYXQiOjE3NjU1NTYyNDAsImp0aSI6IjRmNzBiZDg2NjkwYjQxYjRiMWUwNDFkYmI3Y2JmZGU2IiwidXNlcl9pZCI6IjEifQ.8-LrNhAMN1-27Lw1vyLmFHSlpnC9EcdKo7kI6vSCdBo
###Getting specific reminder
GET http://127.0.0.1:8000/api/reminders/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTU5ODQwLCJpYXQiOjE3NjU1NTYyNDAsImp0aSI6IjRmNzBiZDg2NjkwYjQxYjRiMWUwNDFkYmI3Y2JmZGU2IiwidXNlcl9pZCI6IjEifQ.8-LrNhAMN1-27Lw1vyLmFHSlpnC9EcdKo7kI6vSCdBo
###Updating meeting
PATCH http://127.0.0.1:8000/api/reminders/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTU5ODQwLCJpYXQiOjE3NjU1NTYyNDAsImp0aSI6IjRmNzBiZDg2NjkwYjQxYjRiMWUwNDFkYmI3Y2JmZGU2IiwidXNlcl9pZCI6IjEifQ.8-LrNhAMN1-27Lw1vyLmFHSlpnC9EcdKo7kI6vSCdBo
{
  "title":"Group meeting"
}

###Deleting reminders
DELETE http://127.0.0.1:8000/api/reminders/5/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NTU5ODQwLCJpYXQiOjE3NjU1NTYyNDAsImp0aSI6IjRmNzBiZDg2NjkwYjQxYjRiMWUwNDFkYmI3Y2JmZGU2IiwidXNlcl9pZCI6IjEifQ.8-LrNhAMN1-27Lw1vyLmFHSlpnC9EcdKo7kI6vSCdBo
