@base_url=127.0.0.1:8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NzMwMTMwLCJpYXQiOjE3NjU3MjY1MzAsImp0aSI6IjRhY2ViODc5ZmFjNTQ4MzZhYzVjNmE5YzM0MjE5NjM4IiwidXNlcl9pZCI6IjEifQ.zgpSKT2m_I97WZJqRxJ0Ub4nGGazHDzdYePzcY8CBBg
###Signup
POST http://{{base_url}}/api/register/
Content-Type: application/json

{
    "username": "JudeSedem123",
    "email": "judefiadza@gmail.com",
    "password": "Pass123"
}

###Login
POST http://{{base_url}}/api/login/
Content-Type:application/json

{
    "username": "JudeSedem",
    "password": "Pass123"
}

###Create reminders
POST http://{{base_url}}/api/reminders/
Content-Type:application/json
Authorization: Bearer {{token}}

{
  "title": "Meeting with Gibson",
  "note": "Boo",
  "scheduled_time": "2025-12-14T15:29",
  "frequency": "O"
}


###Listing all reminders
GET http://{{base_url}}/api/reminders/
Authorization: Bearer {{token}}



###Getting specific reminder
GET http://{{base_url}}/api/reminders/12/
Authorization: Bearer {{token}}



###Updating meeting
PATCH http://{{base_url}}/api/reminders/12/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title":"bo23",
  "frequency":"W"
}

###Deleting reminders
DELETE http://{{base_url}}/api/reminders/14/
Content-Type: application/json
Authorization: Bearer {{token}}